In [26]:
import pandas as pd
import sklearn
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [27]:
#ratings = pd.DataFrame()
#for i in range(0,4):
#    if len(ratings) == 0:
#        ratings = pd.read_csv(r"data/user_genre_float/UserRatings_ByGenre" + str(i) + "_f.csv")
#    else:
#        ratings = pd.concat([ratings, pd.read_csv(r"data/user_genre_float/UserRatings_ByGenre" + str(i) + "_f.csv")])

In [28]:
ratings = pd.read_csv("data/UserRatings_ByGenre_all.csv")

In [29]:
clustering_tb = ratings.set_index(ratings.columns[0])

In [30]:
clustering_tb[:5]

,Demons,Super Power,Fantasy,Adventure,Harem,Slice of Life,Sports,Parody,Shounen,Shoujo,...,Mystery,Ecchi,Romance,Psychological,Thriller,Slice of Life,Fantasy,Space,Psychological,Action
Unnamed: 0.1,,,,,,,,,,,,,,,,,,,,,
dabakaguy,2.333333,0.0,1.452107,2.314815,1.116505,1.789474,2.142857,3.333333,0.000000,0.636364,...,1.627451,1.956522,1.020997,0.594595,0.0,1.529032,1.166667,2.033333,0.00,1.612195
AluPachi,4.666667,0.0,4.384314,4.679487,3.545455,5.062500,4.512195,1.666667,0.000000,4.827586,...,4.905405,2.846154,4.106109,2.919355,10.0,5.007937,3.666667,2.086957,4.50,3.975669
-Shido-,0.000000,7.0,4.771536,4.571429,5.846847,5.137255,5.122807,0.000000,2.333333,4.103448,...,4.607843,4.526316,5.072072,4.209302,9.0,3.814815,6.200000,4.050000,5.25,5.010395
BlairKS,0.000000,0.0,4.418440,4.945205,2.800000,5.060345,4.929825,0.000000,0.000000,3.152542,...,4.189655,4.444444,4.418972,4.190476,9.0,4.769231,1.333333,3.909091,3.50,4.141700
danidegraus,0.000000,0.0,1.656126,2.175258,1.365385,2.175676,4.142857,0.000000,0.000000,0.600000,...,0.959184,0.346154,1.734899,1.969697,9.0,2.136364,0.000000,0.692308,2.50,1.498715

In [31]:
for i in clustering_tb.columns:
    clustering_tb[i] = clustering_tb[i].map(lambda x: 10 if x > 10 else x)

In [32]:
clustering_tb.describe()

,Demons,Super Power,Fantasy,Adventure,Harem,Slice of Life,Sports,Parody,Shounen,Shoujo,...,Mystery,Ecchi,Romance,Psychological,Thriller,Slice of Life,Fantasy,Space,Psychological,Action
count,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,...,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000,108709.000000
mean,1.409028,0.293944,5.085965,5.254526,4.153316,4.567879,3.798954,0.978091,0.311336,4.233282,...,4.723367,2.840946,5.023288,4.886593,3.296917,4.335366,2.424339,3.210740,2.308557,5.136084
std,2.820962,1.463869,2.397114,2.499980,2.958995,2.844260,3.278981,2.511522,1.503638,2.959097,...,2.685540,3.186280,2.407755,2.736111,4.443105,2.838083,3.089606,3.322350,3.409210,2.319779
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,3.592593,3.757576,1.216667,2.421053,0.000000,0.000000,0.000000,1.458333,...,2.846154,0.000000,3.478261,3.000000,0.000000,2.000000,0.000000,0.000000,0.000000,3.681818
50%,0.000000,0.000000,5.403226,5.666667,4.535211,4.923077,4.000000,0.000000,0.000000,4.571429,...,5.000000,1.166667,5.342105,5.200000,0.000000,4.625000,0.000000,2.461538,0.000000,5.421053
75%,0.000000,0.000000,6.821429,7.062500,6.503597,6.810811,6.750000,0.000000,0.000000,6.666667,...,6.777778,5.800000,6.806283,7.000000,9.000000,6.600000,5.000000,6.218750,5.000000,6.818182
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [33]:
from sklearn.cluster import KMeans

In [34]:
km_5 =  KMeans(n_clusters=5, 
                init='k-means++',
                random_state=0)
km_5.fit(clustering_tb)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [35]:
cluster_df = pd.DataFrame(km_5.cluster_centers_, columns=clustering_tb.columns)

In [56]:
for i in range(len(cluster_df)):
    ss = cluster_df.iloc[i].sort_values()
    print("group",i, "top3:")
    print(np.round(ss[-20:],2),"\n")
    print("worst3",)
    print(np.round(ss[:3],2),"\n")

group 0 top3:
 School           6.89
 Fantasy          6.90
 Slice of Life    6.90
Action            6.91
Drama             6.92
Adventure         6.94
 Police           6.94
 Super Power      6.95
 Romance          6.95
Slice of Life     6.97
 Mystery          6.98
Mystery           6.98
 Supernatural     6.99
 Comedy           7.00
 Shounen          7.01
 Adventure        7.07
 Psychological    7.08
 Drama            7.10
 Military         7.13
 Thriller         7.27
Name: 0, dtype: float64

worst3
Martial Arts    0.01
Yaoi            0.05
Shoujo          0.19
Name: 0, dtype: float64

group 1 top3:
Mystery           3.38
 Mystery          3.43
 Police           3.45
 Thriller         3.52
 Sci-Fi           3.53
Adventure         3.54
 Military         3.61
 Psychological    3.63
Comedy            3.70
 Magic            3.81
 School           3.97
 Romance          4.18
 Super Power      4.26
 Fantasy          4.37
 Supernatural     4.38
Action            4.47
 Drama            4.49
 Adventure        4.51
 Shounen          4.60
 Comedy           4.61
Name: 1, dtype: float64

worst3
Martial Arts    0.00
Yaoi            0.01
Police          0.03
Name: 1, dtype: float64

group 2 top3:
 Shoujo           0.98
Mystery           1.01
 Military         1.02
 Magic            1.02
Adventure         1.03
 Police           1.04
Slice of Life     1.06
Comedy            1.10
 Psychological    1.10
 Thriller         1.14
 School           1.22
 Romance          1.24
 Fantasy          1.27
 Supernatural     1.33
 Super Power      1.34
 Drama            1.35
 Adventure        1.41
Action            1.44
 Shounen          1.48
 Comedy           1.53
Name: 2, dtype: float64

worst3
Martial Arts    0.00
Police          0.01
Yaoi            0.01
Name: 2, dtype: float64

group 3 top3:
 Seinen           6.24
 Thriller         6.35
Adventure         6.37
Mystery           6.38
 Mystery          6.53
Comedy            6.59
 Magic            6.67
 School           6.70
 Sci-Fi           6.71
 Psychological    6.75
 Military         6.75
 Super Power      6.85
 Romance          6.87
 Fantasy          6.95
 Supernatural     6.96
Action            6.96
 Comedy           7.01
 Shounen          7.04
 Adventure        7.07
 Drama            7.10
Name: 3, dtype: float64

worst3
Martial Arts    0.00
Yaoi            0.01
Super Power     0.03
Name: 3, dtype: float64

group 4 top3:
Mystery           4.83
Slice of Life     4.83
 Mystery          4.85
 Magic            4.86
 Police           4.89
Adventure         4.90
 Romance          4.90
Action            4.92
 School           4.93
 Fantasy          4.93
 Psychological    4.99
 Supernatural     5.02
 Military         5.06
 Super Power      5.08
 Drama            5.08
 Comedy           5.09
 Shounen          5.10
 Adventure        5.19
 Thriller         5.31
Thriller          6.19
Name: 4, dtype: float64

worst3
Martial Arts    0.00
Yaoi            0.03
Shoujo          0.08
Name: 4, dtype: float64

In [42]:
C_recommend = {}

In [43]:
for i in range(len(cluster_df)):
    ss = cluster_df.iloc[i].sort_values()
    C_recommend[i] = {}
    C_recommend[i]["genre"] = [j for j in ss.index[-10:]]

In [44]:
C_recommend

{0: {'genre': [' Mystery',
   'Mystery',
   ' Supernatural',
   ' Comedy',
   ' Shounen',
   ' Adventure',
   ' Psychological',
   ' Drama',
   ' Military',
   ' Thriller']},
 1: {'genre': [' School',
   ' Romance',
   ' Super Power',
   ' Fantasy',
   ' Supernatural',
   'Action',
   ' Drama',
   ' Adventure',
   ' Shounen',
   ' Comedy']},
 2: {'genre': [' School',
   ' Romance',
   ' Fantasy',
   ' Supernatural',
   ' Super Power',
   ' Drama',
   ' Adventure',
   'Action',
   ' Shounen',
   ' Comedy']},
 3: {'genre': [' Military',
   ' Super Power',
   ' Romance',
   ' Fantasy',
   ' Supernatural',
   'Action',
   ' Comedy',
   ' Shounen',
   ' Adventure',
   ' Drama']},
 4: {'genre': [' Psychological',
   ' Supernatural',
   ' Military',
   ' Super Power',
   ' Drama',
   ' Comedy',
   ' Shounen',
   ' Adventure',
   ' Thriller',
   'Thriller']}}

In [58]:
Group_1 = [ "Military", "Sci-Fi"]
Group_2 = [' Comedy', ' Shounen', 'Action']
Group_3 = [' Thriller', 'Thriller', ' Adventure',' Super Power']

In [46]:
anime_info = pd.read_csv("data/anime_cleaned.csv")

In [47]:
anime_info.columns

Index(['anime_id', 'title', 'title_english', 'title_japanese',
       'title_synonyms', 'image_url', 'type', 'source', 'episodes', 'status',
       'airing', 'aired_string', 'aired', 'duration', 'rating', 'score',
       'scored_by', 'rank', 'popularity', 'members', 'favorites', 'background',
       'premiered', 'broadcast', 'related', 'producer', 'licensor', 'studio',
       'genre', 'opening_theme', 'ending_theme', 'duration_min',
       'aired_from_year'],
      dtype='object')

In [67]:
anime_info.sort_values("score", ascending = False)[['anime_id', 'title', 'rating', 'score']]

,anime_id,title,rating,score
6663,37405,Dokidoki Little Ooyasan,Rx - Hentai,9.52
1261,5114,Fullmetal Alchemist: Brotherhood,R - 17+ (violence & profanity),9.25
529,32281,Kimi no Na wa.,PG-13 - Teens 13 or older,9.19
639,28977,GintamaÂ°,R - 17+ (violence & profanity),9.15
2953,30484,Steins;Gate 0,PG-13 - Teens 13 or older,9.15
1475,9253,Steins;Gate,PG-13 - Teens 13 or older,9.14
6100,820,Ginga Eiyuu Densetsu,R - 17+ (violence & profanity),9.11
223,11061,Hunter x Hunter (2011),PG-13 - Teens 13 or older,9.11
4284,9969,Gintama&#039;,PG-13 - Teens 13 or older,9.11
668,35180,3-gatsu no Lion 2nd Season,PG-13 - Teens 13 or older,9.10
2774,15417,Gintama&#039;: Enchousen,PG-13 - Teens 13 or older,9.07
3156,28851,Koe no Katachi,PG-13 - Teens 13 or older,9.04
6331,15335,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,PG-13 - Teens 13 or older,9.04
5219,34096,Gintama.,PG-13 - Teens 13 or older,9.02
3181,35247,Owarimonogatari 2nd Season,R - 17+ (violence & profanity),9.02
3147,918,Gintama,PG-13 - Teens 13 or older,9.01
1366,4181,Clannad: After Story,PG-13 - Teens 13 or older,9.01
3121,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,PG-13 - Teens 13 or older,8.99
3550,2904,Code Geass: Hangyaku no Lelouch R2,R - 17+ (violence & profanity),8.95
3404,199,Sen to Chihiro no Kamikakushi,PG - Children,8.92
2485,34599,Made in Abyss,R - 17+ (violence & profanity),8.91
5579,23273,Shigatsu wa Kimi no Uso,PG-13 - Teens 13 or older,8.88
205,33095,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,PG-13 - Teens 13 or older,8.87
434,28891,Haikyuu!! Second Season,PG-13 - Teens 13 or older,8.87
2658,31758,Kizumonogatari III: Reiketsu-hen,R - 17+ (violence & profanity),8.87
90,36838,Gintama.: Shirogane no Tamashii-hen,PG-13 - Teens 13 or older,8.85
1889,24701,Mushishi Zoku Shou 2nd Season,PG-13 - Teens 13 or older,8.83
4358,1,Cowboy Bebop,R - 17+ (violence & profanity),8.81
1013,164,Mononoke Hime,PG-13 - Teens 13 or older,8.80
6165,263,Hajime no Ippo,PG-13 - Teens 13 or older,8.80
...,...,...,...,...
4652,22669,Gohan Kaijuu Pap,G - All Ages,3.69
2001,36764,Tripod Baby,G - All Ages,3.67
2087,33342,Ari to Kirigirisu,G - All Ages,3.60
3701,32402,Mim Mam Mint,G - All Ages,3.58
3611,29361,Kareshi wa Hammerhead Shark,PG - Children,3.58
5979,28929,Vampire Holmes,PG-13 - Teens 13 or older,3.54
2372,33696,3D Onara Gorou ga Dance Dance Dance!!,G - All Ages,3.51
735,32999,"Neko mo, Onda-ke",G - All Ages,3.51
5593,35590,Aware! Meisaku-kun: DVD Hatsubai Kettei!,G - All Ages,3.46
6133,37678,Aware! Meisaku-kun: Short Douga,G - All Ages,3.44
57,33398,Neko Konogoro,None,3.44
857,33922,"Taka no Tsume-dan, Toyama",G - All Ages,3.40
5958,24403,Nyanpuku Nyaruma,G - All Ages,3.35
1444,34720,In Search of Axis,G - All Ages,3.31
4377,32388,Undouki Kenshin Manual Taiou Taisou,G - All Ages,3.25
2294,2792,Panzer Dragoon,PG-13 - Teens 13 or older,3.21
3693,34628,Taka no Tsume x Hello Kitty ga Masaka no Collab!,G - All Ages,3.19
2373,36349,Gum Shaara,G - All Ages,2.89
6625,36579,Fettu to Ccine to Gummi Seijin,PG - Children,2.86
5988,35563,Ore to Issho ni Training,PG-13 - Teens 13 or older,2.71
1781,5877,Abunai Sisters: Koko & Mika,R+ - Mild Nudity,2.61
4057,413,Hametsu no Mars,R - 17+ (violence & profanity),2.33
4695,35656,Oshiri Tantei,PG - Children,2.33
6636,37020,Woo to Wah,G - All Ages,1.00
6652,37858,Free! Movie 1: Timeless Medley - Kizuna: Chara...,PG-13 - Teens 13 or older,0.00
6640,37814,Inazuma Eleven Reloaded: Reformation of Soccer,G - All Ages,0.00
6644,37860,Free!: Take Your Marks: Character Butai Aisatsu,PG-13 - Teens 13 or older,0.00
6661,37494,Chikyuu to no Yakusoku,G - All Ages,0.00
6648,37859,Free! Movie 2: Timeless Medley - Yakusoku: Cha...,PG-13 - Teens 13 or older,0.00
6664,37886,Wo Shi Jiang Xiaobai (2018),PG-13 - Teens 13 or older,0.00

In [48]:
def intersection(lst1, lst2): 
    return list(set(lst1) & set(lst2))

In [59]:
Group_1_anime = []
Group_2_anime = []
Group_3_anime = []

for i in range(anime_info.shape[0]):
    try:
        this_genre = anime_info["genre"].iloc[i].split(",")
    except:
        print(anime_info["genre"].iloc[i])
    if len(intersection(this_genre, Group_1)) >=1 :
        Group_1_anime.append((anime_info["anime_id"].iloc[i], anime_info["title"].iloc[i], anime_info["score"].iloc[i]))
    if len(intersection(this_genre, Group_2)) >=2 :
        Group_2_anime.append((anime_info["anime_id"].iloc[i], anime_info["title"].iloc[i],  anime_info["score"].iloc[i]))
    if len(intersection(this_genre, Group_3)) >=2 :
        Group_3_anime.append((anime_info["anime_id"].iloc[i],anime_info["title"].iloc[i],  anime_info["score"].iloc[i]))

nan
nan
nan
nan

In [60]:
len(Group_1_anime)

281

In [61]:
Group_1_anime.sort(key=lambda x: x[2], reverse=True)
Group_2_anime.sort(key=lambda x: x[2], reverse=True)
Group_3_anime.sort(key=lambda x: x[2], reverse=True)

In [62]:
Group_1_anime[:20]

[(30484, 'Steins;Gate 0', 9.15),
 (820, 'Ginga Eiyuu Densetsu', 9.11),
 (34599, 'Made in Abyss', 8.91),
 (11577, 'Steins;Gate Movie: Fuka Ryouiki no DÃ©jÃ  vu', 8.58),
 (13125, 'Shinsekai yori', 8.49),
 (32, 'Neon Genesis Evangelion: The End of Evangelion', 8.48),
 (10863, 'Steins;Gate: Oukoubakko no Poriomania', 8.44),
 (34240, 'Shelter', 8.41),
 (338, 'Versailles no Bara', 8.38),
 (2236, 'Toki wo Kakeru Shoujo', 8.35),
 (32188, 'Steins;Gate: Kyoukaimenjou no Missing Link - Divide By Zero', 8.33),
 (33970, 'Girls & Panzer: Saishuushou', 8.25),
 (5681, 'Summer Wars', 8.22),
 (1257, 'Saint Seiya: Meiou Hades Juuni Kyuu-hen', 8.2),
 (3167, 'Eve no Jikan', 8.19),
 (7465, 'Eve no Jikan (Movie)', 8.17),
 (12477, 'Sakasama no Patema', 8.17),
 (237, 'Eureka Seven', 8.15),
 (1943, 'Paprika', 8.12),
 (1023, 'Wolf&#039;s Rain OVA', 8.1)]

In [23]:
Group_2_anime[:10]

[(5114, 'Fullmetal Alchemist: Brotherhood', 9.25),
 (28977, 'GintamaÂ°', 9.15),
 (11061, 'Hunter x Hunter (2011)', 9.11),
 (9969, 'Gintama&#039;', 9.11),
 (15417, 'Gintama&#039;: Enchousen', 9.07),
 (15335, 'Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare', 9.04),
 (34096, 'Gintama.', 9.02),
 (918, 'Gintama', 9.01),
 (36838, 'Gintama.: Shirogane no Tamashii-hen', 8.85),
 (1, 'Cowboy Bebop', 8.81)]

In [24]:
Group_3_anime[:10]

[(11061, 'Hunter x Hunter (2011)', 9.11),
 (21, 'One Piece', 8.54),
 (136, 'Hunter x Hunter', 8.47),
 (137, 'Hunter x Hunter: Yorkshin City Kanketsu-hen', 8.39),
 (139, 'Hunter x Hunter: Greed Island Final', 8.38),
 (813, 'Dragon Ball Z', 8.31),
 (138, 'Hunter x Hunter: Greed Island', 8.3),
 (9130, 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2', 8.29),
 (19123,
  'One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari',
  8.28),
 (15323,
  'One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna',
  8.23)]

In [134]:
Group_2_anime[0][2]

2.61

## Mapping to users

In [12]:
user_group = pd.DataFrame(km_5.labels_, index = clustering_tb.index, columns=["group"])

In [13]:
user_group[:5]

              group
Unnamed: 0.1
dabakaguy         2
AluPachi          4
-Shido-           4
BlairKS           4
danidegraus       2

In [14]:
user_info = pd.read_csv("data/users_cleaned.csv")

In [15]:
user_info.columns

Index(['username', 'user_id', 'user_watching', 'user_completed', 'user_onhold',
       'user_dropped', 'user_plantowatch', 'user_days_spent_watching',
       'gender', 'location', 'birth_date', 'access_rank', 'join_date',
       'last_online', 'stats_mean_score', 'stats_rewatched', 'stats_episodes'],
      dtype='object')

In [16]:
user_InfoGroup = pd.merge(user_group, user_info[['username', 'user_id','gender', 'location', 'birth_date' ]],
                         left_index= True, right_on = 'username')

In [17]:
user_InfoGroup["birth_date"] = user_InfoGroup["birth_date"].map(lambda x: pd.to_datetime(x.split(" ")[0]))

In [18]:
user_InfoGroup["age"] = user_InfoGroup["birth_date"].map(lambda x: pd.to_datetime("2018-12-03").year - x.year)

In [19]:
user_InfoGroup[:5]

        group     username  user_id gender          location birth_date  age
102182      2    dabakaguy  4214517   Male            Hawaii 1986-12-19   32
88063       4     AluPachi  2056043   Male          Austria  1990-10-01   28
52790       4      -Shido-  4265141   Male           Aincrad 1999-04-02   19
7870        4      BlairKS   892751   Male  Kaneohe, Hawai'i 1995-06-27   23
74782       2  danidegraus  5322209   Male  Barcelona, Spain 1989-11-28   29

In [25]:
def q_1(array):
    return np.percentile(array, 25)
def q_3(array):
    return np.percentile(array, 75)

In [26]:
user_InfoGroup.groupby("group")["age"].agg({"mean": np.mean, 
                                            "3rd_quantile": q_3, 
                                            "1st_quantile": q_1})

/Users/chunhsiangchang/anaconda2/envs/Python3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  This is separate from the ipykernel package so we can avoid doing imports until

            mean  3rd_quantile  1st_quantile
group
0      26.168464            29            23
1      24.563720            27            21
2      24.667528            27            22
3      25.958418            29            23
4      24.355809            27            21

In [27]:
user_InfoGroup.groupby(["group", "gender"])["gender"].count()

group  gender
0      Female         4983
       Male          15823
       Non-Binary       59
1      Female        11642
       Male          15340
       Non-Binary      129
2      Female         6461
       Male           8148
       Non-Binary      105
3      Female         7904
       Male          14300
       Non-Binary       41
4      Female         6340
       Male          17267
       Non-Binary      167
Name: gender, dtype: int64

In [40]:
country = user_InfoGroup.groupby(["group", "location"])["location"].count()

In [43]:
country[country > 100].loc[0].sort_values(ascending = False)

location
Poland            324
Germany           246
Brazil            238
France            199
Canada            153
California        153
Philippines       149
Russia            142
Singapore         136
Finland           126
Moscow, Russia    108
Brasil            107
Sweden            106
Indonesia         106
Portugal          104
Name: location, dtype: int64

In [45]:
country[country > 100].loc[1].sort_values(ascending = False)

location
Poland             406
Germany            241
California         227
Canada             225
Brazil             205
Portugal           176
Philippines        173
Sweden             170
England            154
Australia          152
The Netherlands    144
Singapore          141
France             135
Norway             131
Netherlands        124
Texas              123
London             121
Finland            119
UK                 115
New York           107
Belgium            106
Brasil             102
USA                102
Name: location, dtype: int64

In [46]:
country[country > 100].loc[2].sort_values(ascending = False)

location
Poland         223
Germany        178
Canada         149
Brazil         136
California     119
Philippines    108
Portugal       102
Name: location, dtype: int64

In [47]:
country[country > 100].loc[3].sort_values(ascending = False)

location
Poland         266
Germany        171
Philippines    157
Brazil         156
California     153
Canada         142
England        127
Singapore      117
Australia      109
Sweden         108
Name: location, dtype: int64

In [48]:
country[country > 100].loc[4].sort_values(ascending = False)

location
Poland             437
Germany            296
France             288
Brazil             287
Canada             231
California         196
Sweden             183
Portugal           176
Brasil             140
Finland            135
Netherlands        131
Norway             130
England            127
Australia          121
The Netherlands    120
Philippines        116
Italy              107
Name: location, dtype: int64