In [14]:
%matplotlib inline
import pandas as pd
import numpy as np

data = pd.read_csv('anime_cleaned.csv/anime_cleaned.csv')
data[:5]

,anime_id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,broadcast,related,producer,licensor,studio,genre,opening_theme,ending_theme,duration_min,aired_from_year
0,11013,Inu x Boku SS,Inu X Boku Secret Service,妖狐×僕SS,Youko x Boku SS,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,Fridays at Unknown,"{'Adaptation': [{'mal_id': 17207, 'type': 'man...","Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"Comedy, Supernatural, Romance, Shounen","['""Nirvana"" by MUCC']","['#1: ""Nirvana"" by MUCC (eps 1, 11-12)', '#2: ...",24.0,2012.0
1,2104,Seto no Hanayome,My Bride is a Mermaid,瀬戸の花嫁,The Inland Sea Bride,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 759, 'type': 'manga...","TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"Comedy, Parody, Romance, School, Shounen","['""Romantic summer"" by SUN&LUNAR']","['#1: ""Ashita e no Hikari (明日への光)"" by Asuka Hi...",24.0,2007.0
2,5262,Shugo Chara!! Doki,Shugo Chara!! Doki,しゅごキャラ！！どきっ,"Shugo Chara Ninenme, Shugo Chara! Second Year",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 101, 'type': 'manga...","TV Tokyo, Sotsu",NaN,Satelight,"Comedy, Magic, School, Shoujo","['#1: ""Minna no Tamago (みんなのたまご)"" by Shugo Cha...","['#1: ""Rottara Rottara (ロッタラ ロッタラ)"" by Buono! ...",24.0,2008.0
3,721,Princess Tutu,Princess Tutu,プリンセスチュチュ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,...,Fridays at Unknown,"{'Adaptation': [{'mal_id': 1581, 'type': 'mang...","Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy","['""Morning Grace"" by Ritsuko Okazaki']","['""Watashi No Ai Wa Chiisaikeredo"" by Ritsuko ...",16.0,2002.0
4,12365,Bakuman. 3rd Season,Bakuman.,バクマン。,Bakuman Season 3,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 9711, 'type': 'mang...","NHK, Shueisha",NaN,J.C.Staff,"Comedy, Drama, Romance, Shounen","['#1: ""Moshimo no Hanashi (もしもの話)"" by nano.RIP...","['#1: ""Pride on Everyday"" by Sphere (eps 1-13)...",24.0,2012.0

In [2]:
data['airing'].value_counts()

False    6485
True      183
Name: airing, dtype: int64

In [3]:
data[['genre','score']].groupby('genre').agg(['count','mean'])['score'].sort_values(by='count', ascending=False)[:10]

                       count      mean
genre
Hentai                   244  6.644631
Comedy                   216  5.898056
Music                     80  6.293875
Slice of Life, Comedy     67  6.594776
Comedy, Slice of Life     48  6.555000
Slice of Life             46  5.600000
Comedy, Kids              39  5.672051
Fantasy                   38  6.243684
Kids                      38  5.469474
Adventure, Fantasy        33  6.536667

In [18]:
data[['rating','score']].groupby('rating').agg(['count','mean'])['score'].sort_values(by='count', ascending=False)[:10]

                                count      mean
rating
PG-13 - Teens 13 or older        3396  7.034485
G - All Ages                     1046  6.297878
R - 17+ (violence & profanity)    758  7.223826
R+ - Mild Nudity                  566  6.779505
PG - Children                     488  6.555820
Rx - Hentai                       332  6.577681
None                               82  6.055366

In [4]:
data[['type','score']].groupby('type').agg(['count','mean'])['score'].sort_values(by='count', ascending=False)[:10]

         count      mean
type
TV        2980  7.020124
OVA       1345  6.694379
Special    929  6.714618
Movie      908  7.100837
ONA        408  6.066544
Music       98  5.965510

In [17]:
data[['title','score','rank','scored_by','popularity','members','favorites']].sort_values(by=['popularity'])[:20]

,title,score,rank,scored_by,popularity,members,favorites
3802,Death Note,8.67,51.0,1009477,1,1456378,88696
3897,Shingeki no Kyojin,8.49,110.0,940211,2,1345842,64032
3009,Sword Art Online,7.64,1259.0,915986,3,1301616,50042
1261,Fullmetal Alchemist: Brotherhood,9.25,1.0,733592,4,1199091,106895
4215,One Punch Man,8.73,44.0,691845,5,1020754,30747
630,Tokyo Ghoul,8.00,560.0,659308,6,1013138,28883
6523,Angel Beats!,8.31,227.0,641851,7,1010771,36456
1475,Steins;Gate,9.14,5.0,563857,8,1010330,92423
6579,Code Geass: Hangyaku no Lelouch,8.79,30.0,627740,9,986897,63614
2199,Naruto,7.88,745.0,648605,10,980265,34468
3108,No Game No Life,8.41,162.0,623227,11,970460,31782
4379,Mirai Nikki (TV),7.89,721.0,592994,12,964441,23674
19,Toradora!,8.39,174.0,557898,13,910373,35322
2625,Ao no Exorcist,7.83,823.0,521881,14,863098,13130
3022,Noragami,8.15,377.0,502213,15,846498,18501
4171,Elfen Lied,7.75,982.0,514656,16,833388,20137
2538,Sword Art Online II,7.20,2827.0,531486,17,830508,7931
14,Bleach,7.90,693.0,433097,18,819284,40718
116,Fairy Tail,8.08,452.0,423745,19,818652,37733
17,Naruto: Shippuuden,8.18,337.0,385179,20,794112,42846

In [45]:
data[['producer','score']].groupby('producer').agg(['count','mean'])['score'].sort_values(by='count', ascending=False)[:10]

                   count      mean
producer
Aniplex               71  7.188592
Pink Pineapple        66  6.847424
Bandai Visual         65  6.965692
NHK                   60  6.689000
TV Tokyo              56  6.738036
Fuji TV               53  6.918302
TV Asahi              44  7.017273
Shueisha              40  6.877500
Starchild Records     40  6.913750
Lantis                35  6.930857

In [53]:
data[['studio','score']].groupby('studio').agg(['count','mean'])['score'].sort_values(by='count', ascending=False)[:10]

                   count      mean
studio
Toei Animation       403  6.970372
Sunrise              277  7.227401
Madhouse             243  7.178765
Studio Pierrot       235  6.874723
J.C.Staff            233  6.976137
Studio Deen          204  7.118971
Production I.G       178  7.151573
A-1 Pictures         159  7.253270
TMS Entertainment    155  7.154387
OLM                  135  6.726889

In [16]:
from sklearn.linear_model import LinearRegression
from scipy import stats

X = data[['episodes', 'scored_by', 'favorites', 'duration_min']]
y = data['score']
lm = LinearRegression()
result = lm.fit(X,y)
params = np.append(lm.intercept_,lm.coef_)
predictions = lm.predict(X)

newX = pd.DataFrame({"Constant":np.ones(len(X))}).join(pd.DataFrame(X))
MSE = (sum((y-predictions)**2))/(len(newX)-len(newX.columns))

var_b = MSE*(np.linalg.inv(np.dot(newX.T,newX)).diagonal())
sd_b = np.sqrt(var_b)
ts_b = params/ sd_b

p_values =[2*(1-stats.t.cdf(np.abs(i),(len(newX)-1))) for i in ts_b]

#sd_b = np.round(sd_b,3)
#ts_b = np.round(ts_b,3)
#p_values = np.round(p_values,3)
#params = np.round(params,4)

df = pd.DataFrame()
df["Coefficients"],df["Standard Errors"],df["t values"],df["Probabilites"] = [params,sd_b,ts_b,p_values]
df['Name'] = ['int','episodes', 'scored_by', 'favorites', 'duration_min']
col = ['Name', 'Coefficients', 'Standard Errors', 't values', 'Probabilites']
df = df[col]
print(df)

           Name  Coefficients  Standard Errors    t values  Probabilites
0           int      6.374538     1.604686e-02  397.245261  0.000000e+00
1      episodes      0.002004     2.455127e-04    8.162112  4.440892e-16
2     scored_by      0.000007     2.678918e-07   25.644271  0.000000e+00
3     favorites     -0.000028     4.291590e-06   -6.419714  1.459155e-10
4  duration_min      0.010520     3.945637e-04   26.661620  0.000000e+00

In [135]:
X = data[['source','episodes', 'scored_by', 'favorites', 'duration_min','rating','producer','studio','genre']]
X = pd.get_dummies(X)
lm.fit(X,y)
coefficients = pd.concat([pd.DataFrame(X.columns),pd.DataFrame(np.transpose(lm.coef_))], axis = 1)
coefficients.columns = ['Var', 'Coef']
coefficients.sort_values(by='Coef', ascending = False)

                                                    Var      Coef
3825  genre_Action, Horror, Demons, Supernatural, Ro...  4.333655
2256  producer_VAP, Big West, King Records, Media Ri...  4.101783
6316                             genre_Thriller, Sci-Fi  4.050760
5835           genre_Mystery, Horror, Thriller, Shounen  3.827748
2176             producer_Tencent Animation, Studio LAN  3.451745
5211           genre_Drama, Game, Seinen, Slice of Life  3.321614
5857           genre_Mystery, Sci-Fi, Shounen, Thriller  3.130680
6296    genre_Super Power, Magic, Martial Arts, Fantasy  3.102274
1326  producer_Media Factory, Shochiku, Yomiko Adver...  3.074147
4252       genre_Action, Space, Military, Drama, Sci-Fi  3.018558
5825  genre_Mystery, Historical, Horror, Demons, Psy...  2.923576
1247                                   producer_Level-5  2.889606
5740                     genre_Military, Sports, School  2.858439
3668  genre_Action, Drama, Shounen, Slice of Life, S...  2.832252
3662  genre_Action, Drama, Sci-Fi, Shounen, Slice of...  2.818141
4463                   genre_Adventure, Demons, Fantasy  2.807290
6114  genre_Slice of Life, Comedy, Drama, Romance, S...  2.749267
1495                 producer_Pony Canyon, Animation Do  2.665878
2185                         producer_The Answer Studio  2.654987
4987       genre_Comedy, Mystery, Supernatural, Vampire  2.654281
5387                     genre_Fantasy, Dementia, Drama  2.647796
770                     producer_Fuji TV, TAP, Shueisha  2.645247
3377      genre_Action, Adventure, Super Power, Shounen  2.601935
3325  genre_Action, Adventure, Mecha, Drama, Sci-Fi,...  2.585389
3795  genre_Action, Historical, Drama, Romance, Mart...  2.545458
4214    genre_Action, Sci-Fi, Space, Super Power, Mecha  2.535966
4129  genre_Action, Sci-Fi, Comedy, Romance, Fantasy...  2.521754
5676                   genre_Magic, Fantasy, Shounen Ai  2.519251
4985                 genre_Comedy, Mystery, Super Power  2.517089
185   producer_Aniplex, Lantis, Cospa, Studio Mausu,...  2.515981
...                                                 ...       ...
3015                                        studio_TUBA -2.075121
1596          producer_Shanghai Jump Network Technology -2.080372
928   producer_Geneon Universal Entertainment, TBS, ... -2.104127
1563                         producer_Quick Corporation -2.142704
622   producer_Dentsu, Lantis, Mainichi Broadcasting... -2.149094
2528        studio_CoMix Wave Films, FOREST Hunting One -2.158652
210   producer_Aniplex, Movic, ASCII Media Works, Ju... -2.181778
2512                                      studio_Bridge -2.205611
1901  producer_TBS, Nippon Columbia, Zack Promotion,... -2.207939
1741  producer_Sotsu, Nomad, Bushiroad, Chrono Gear ... -2.218982
5407               genre_Fantasy, Horror, Psychological -2.226335
323   producer_Avex Entertainment, Marvelous, Lantis... -2.235079
2806                              studio_Pie in The Sky -2.257314
605   producer_Dentsu, Frontier Works, Mainichi Broa... -2.267628
2594                          studio_Gainax, Studio 4°C -2.280054
2315                                     producer_WOWOW -2.281965
633   producer_Dentsu, Shochiku, Kodansha, Ai Addict... -2.409431
860   producer_Genco, Movic, Warner Bros., KlockWorx... -2.419011
1224  producer_Lantis, Pony Canyon, TBS, Rakuonsha, ... -2.519921
5735      genre_Military, Sci-Fi, Space, Comedy, Parody -2.707426
1973               producer_TV Tokyo, Aniplex, Shueisha -3.126379
1996  producer_TV Tokyo, Bandai Visual, Lantis, Asat... -3.231136
5803               genre_Mystery, Comedy, Kids, Fantasy -3.258904
625   producer_Dentsu, Mainichi Broadcasting System,... -3.298925
2405                              studio_2:10 Animation -3.436170
2985                              studio_Studio! Cucuri -3.468288
318   producer_Avex Entertainment, Dentsu, Shochiku,... -3.653703
159   producer_Aniplex, Genco, DAX Production, ASCII... -3.922724
137   producer_Aniplex, Dentsu, Mainichi Broadcastin... -4.302376
158   producer_Aniplex, Genco, ASCII Media Works, Ba... -5.281408

[6318 rows x 2 columns]